---
- name: Configure kibana # скачиваем template. Выполняется после download и install tasks
  become: true
  template:
    src: kibana.yml.j2
    mode: 0644
    dest: /etc/kibana/kibana.yml
  notify: restart kibana
