---
- name: "Download Kibana's rpm" # производится закгрузка пакета установки Kibana. Выполняется в зависимости от значения переменно ansible_facts.pkg_mgr (значение получает при сборе фактов о хосте). Выполняется для centos
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-x86_64.rpm"
    dest: "files/kibana-{{ kibana_version }}-x86_64.rpm"
    validate_certs: false
  register: download_kibana
  delegate_to: localhost
  until: download_kibana is succeeded
  when: kibana_install_type == 'remote'
- name: Copy Kibana to managed node
  copy:
    src: "files/kibana-{{ kibana_version }}-x86_64.rpm"
    mode: 0755
    dest: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
