---
- name: Install Kibana # выполняется установка пакета, task выполняется в зависимости от значения в переменной ansible_facts.pkg_mgr
  become: true
  yum:
    name: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
    state: present
  notify: restart kibana
