---
- name: restart kibana # handler для перезапуска сервиса
  become: true
  service:
    name: kibana
    state: restarted
  when: ansible_virtualization_type != 'docker' # проверка, что сервис запущен не на docker
